image: node:18

pages:
  stage: deploy
  script:
    - npm install --legacy-peer-deps
    - npx expo export:web
    - cp -r web-build/* public/
  artifacts:
    paths:
      - public
  only:
    - main 