image: node:18

pages:
  stage: deploy
  script:
    - npm install --legacy-peer-deps
    - npx expo export:web
    - mkdir -p public
    - cp -r web-build/* public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH 